### ISSUE TITLE
Go panic during session_created

### ISSUE THREAD

**Issue by tsavola** [ninchat/ninchat-python#8]
```
2017-12-19 18:04:07,183 ninchat.client: session 1.0: opening
2017-12-19 18:04:07,183 ninchat.client: session 1.0: endpoint discovery
2017-12-19 18:04:07,491 ninchat.client: session 1.0: endpoint discovered
2017-12-19 18:04:07,491 ninchat.client: session 1.0: connecting to z-18-195-134-150.ninchat.com
2017-12-19 18:04:07,783 ninchat.client: session 1.0: connected
2017-12-19 18:04:07,783 ninchat.client: session 1.0: session creation
2017-12-19 18:04:08,004 ninchat.bot: event: session_created
2017-12-19 18:04:08,004 ninchat.bot: user 57v3uudg00guc: loading history
2017-12-19 18:04:08,004 ninchat.client: session 1.1: session created
panic: send on closed channel

goroutine 29 [running]:
github.com/ninchat/ninchat-go.(*Session).sendAck.func1(0xc42007cdd0)
	/home/user/src/github.com/ninchat/ninchat-python/go/src/github.com/ninchat/ninchat-go/session.go:252 +0x3b
created by github.com/ninchat/ninchat-go.(*Session).sendAck
	/home/user/src/github.com/ninchat/ninchat-python/go/src/github.com/ninchat/ninchat-go/session.go:250 +0x48
```

**Comment by tsavola** [comment]
It seems to be a client code error.
